# Generated by Django 3.0.2 on 2021-01-19 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, null=True)),
                ('real_path', models.TextField(null=True)),
                ('parent_key', models.TextField(null=True)),
                ('parent_title', models.TextField(null=True)),
                ('parent_path', models.TextField(null=True)),
                ('create_dttm', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'manual_category',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('category_key', models.TextField(null=True)),
                ('file_name', models.TextField(null=True)),
                ('real_path', models.TextField(null=True, unique=True)),
                ('writer', models.CharField(max_length=10, null=True)),
                ('modifier', models.CharField(max_length=10, null=True)),
                ('create_dttm', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_dttm', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'manual_document',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.TextField(null=True)),
                ('real_path', models.TextField(null=True)),
                ('modifier', models.CharField(max_length=10, null=True)),
                ('category_key', models.TextField(null=True)),
                ('method', models.CharField(max_length=30, null=True)),
                ('create_dttm', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'manual_history',
            },
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.TextField(null=True)),
                ('real_path', models.FileField(null=True, upload_to='uploads/%Y/%m/%d')),
                ('size', models.FloatField(null=True)),
                ('extension', models.CharField(max_length=50)),
                ('create_dttm', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'manual_media',
            },
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['create_dttm'], name='manual_medi_create__204fc7_idx'),
        ),
        migrations.AddIndex(
            model_name='history',
            index=models.Index(fields=['create_dttm'], name='manual_hist_create__d4af1a_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['create_dttm'], name='manual_docu_create__faec7a_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['create_dttm'], name='manual_cate_create__c00e80_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('parent_key', 'real_path')},
        ),
    ]
