# Generated by Django 3.0.2 on 2021-01-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
